### ISSUE TITLE
onedrive路径读取

### ISSUE THREAD

**Issue by valetzx** [arect/onedrive_blog#2]
你好，请问博客内想读取上级文件路径是不是不支持

尝试md以及html“..//”都没有成功 谢谢！

**Comment by arect** [comment]
对的，因为这并不是模拟真的文件系统，如果要对路径进行解析，可能会出现很多意外，所以没有考虑其它文件夹。

**Comment by valetzx** [comment]
> Reference in

好的谢谢，要重新传有点麻烦，想随便写写玩的(
