### ISSUE TITLE
不行了我要笑死自己了

### ISSUE THREAD

**Issue by valetzx** [arect/onedrive_blog#3]
请阅：https://service-pvq8q68z-1254084444.sh.apigw.tencentcs.com/release/onedrive-ppg/pig
上面是新套嵌（）然后想加个一页显示几篇文章，然后能翻页的功能（）要是能读od文件夹然后做音乐,视频轮播之类的就好了（）

**Comment by arect** [comment]
最近在做工作上的事情，没什么时间。
可能要等一个月吧。

**Comment by valetzx** [comment]
好的，昨天发现隔壁alist有音乐播放器好用的很

**Comment by arect** [comment]
正好刚刚写好了分页。已经提交到我的仓库了。
