### ISSUE TITLE
网页error 500

### ISSUE THREAD

**Issue by valetzx** [arect/onedrive_blog#4]
[allblog.vercel.app](https://allblog.vercel.app/)
我是直接复制你代码的，然后你的demo中 `OneDrive/Blog` 字体变黑了
可否加 当前页和总页显示(

<html>
<body>

Cloning github.com/valetzx/allblog (Branch: main, Commit: 9b94437)
--
00:11:50.481 | Cloning completed: 1.043s
00:11:50.515 | Analyzing source code...
00:11:50.827 | Installing build runtime...
00:11:53.721 | Build runtime installed: 2.894s
00:11:54.386 | Looking up build cache...
00:11:57.003 | Build cache downloaded [24.71 MB]: 2346.445ms
00:11:57.131 | Injecting Nuxt.js analytics plugin "@nuxtjs/web-vitals" to `/vercel/path0/.nuxtrc`
00:11:57.136 | Adding "@nuxtjs/web-vitals" to `package.json` "dependencies"
00:11:57.144 | Detected package.json
00:11:57.144 | Installing dependencies...
00:11:57.399 | yarn install v1.22.17
00:11:57.472 | [1/4] Resolving packages...
00:11:58.036 | [2/4] Fetching packages...
00:11:58.044 | warning Pattern ["@nuxt/kit@npm:@nuxt/kit-edge@3.0.0-27333874.279bfdc"] is trying to unpack in the same destination "/vercel/.cache/yarn/v6/npm-@nuxt-kit-3.0.0-27333874.279bfdc-96d68919816761955187113769662cd2192f4eaf-integrity/node_modules/@nuxt/kit" as pattern ["@nuxt/kit@npm:@nuxt/kit-edge@latest"]. This could result in non-deterministic behavior, skipping.
00:12:09.538 | [3/4] Linking dependencies...
00:12:09.540 | warning "nuxt-windicss > vite-plugin-windicss@1.5.4" has unmet peer dependency "vite@^2.0.1".
00:12:09.542 | warning "nuxt3 > @nuxt/vite-builder > autoprefixer@10.4.0" has unmet peer dependency "postcss@^8.1.0".
00:12:09.542 | warning "nuxt3 > @nuxt/vite-builder > postcss-import@14.0.2" has unmet peer dependency "postcss@^8.0.0".
00:12:09.543 | warning "nuxt3 > @nuxt/vite-builder > postcss-url@10.1.3" has unmet peer dependency "postcss@^8.0.0".
00:12:14.665 | [4/4] Building fresh packages...
00:12:14.986 | success Saved lockfile.
00:12:14.991 | Done in 17.60s.
00:12:15.216 | Running "yarn run build"
00:12:15.403 | yarn run v1.22.17
00:12:15.431 | $ nuxi build
00:12:15.521 | [log] Nuxt CLI v3.0.0-27333874.279bfdc
00:12:17.436 | [info] [@nuxtjs/web-vitals] Auto detected provider: vercel
00:12:19.797 | [info] Vite warmed up in 1741ms
00:12:20.571 | [info] Client built in 2513ms
00:12:20.578 | [info] Building server...
00:12:21.269 | [success] Server built in 691ms
00:12:21.270 | [info] Nitro preset is vercel
00:12:21.270 | [info] Cleaning up .vercel_build_output
00:12:21.271 | [start] Generating public...
00:12:21.299 | [success] Generated public .vercel_build_output/static
00:12:21.311 | [start] Building server...
00:12:23.656 | [start] Writing server bundle...
00:12:23.760 | [success] Server built
00:12:23.835 | ├─ .vercel_build_output/functions/node/server/index.mjs (69.3 kB) (23.6 kB gzip)
00:12:23.836 | ├─ .vercel_build_output/functions/node/server/chunks/index2.mjs (392 kB) (90.3 kB gzip)
00:12:23.836 | ├─ .vercel_build_output/functions/node/server/chunks/index.mjs (2.62 kB) (980 B gzip)
00:12:23.836 | ├─ .vercel_build_output/functions/node/server/chunks/getAccessToken.mjs (1.02 kB) (509 B gzip)
00:12:23.836 | ├─ .vercel_build_output/functions/node/server/chunks/article.mjs (2.5 kB) (879 B gzip)
00:12:23.836 | ├─ .vercel_build_output/functions/node/server/chunks/app/vue3.mjs (285 B) (202 B gzip)
00:12:23.837 | ├─ .vercel_build_output/functions/node/server/chunks/app/server.mjs (145 kB) (35.6 kB gzip)
00:12:23.837 | ├─ .vercel_build_output/functions/node/server/chunks/app/render.mjs (22.2 kB) (6.14 kB gzip)
00:12:23.842 | ├─ .vercel_build_output/functions/node/server/chunks/app/config.mjs (2.53 kB) (1.71 kB gzip)
00:12:23.842 | └─ .vercel_build_output/functions/node/server/chunks/app/client.manifest.mjs (1.96 kB) (502 B gzip)
00:12:23.842 | Σ Total size: 1.16 MB (299 kB gzip)
00:12:23.873 | Done in 8.47s.
00:12:24.066 | Detected Serverless Functions in ".vercel_build_output"
00:12:24.067 | Detected Static Assets in ".vercel_build_output"
00:12:24.067 | Detected Routes Configuration in ".vercel_build_output"
00:12:24.073 | Uploading build outputs...
00:12:24.721 | Deploying build outputs...
00:12:29.865 | Build completed. Populating build cache...
00:12:35.925 | Uploading build cache [24.71 MB]...
00:12:37.519 | Build cache uploaded: 1.594s
00:12:37.545 | Done with "package.json"

</body>
</html>

**Comment by valetzx** [comment]
已解决，我21天前的 修复logo没同步。

**Comment by valetzx** [comment]
不过似乎没有读取我的setting设置 [https://allblog.vercel.app/](https://allblog.vercel.app/)
![image](https://user-images.githubusercontent.com/45054400/154104847-57d9a6ac-0d41-4269-b161-5f235827f3ba.png)
![image](https://user-images.githubusercontent.com/45054400/154104979-45342a16-6509-4523-8f86-e4ccac80c72f.png)

**Comment by valetzx** [comment]
emm甚至吞了几篇文章，好乱()

**Comment by arect** [comment]
从你的仓库下载来看，好像没有问题。
![image](https://user-images.githubusercontent.com/40746088/154185321-7f76b0e7-83cc-44f8-a282-675218412b5d.png)

**Comment by valetzx** [comment]
好的我把vercel删了重新部署看看

**Comment by valetzx** [comment]
这两个Warning他正常吗
<html>
<body>


[1/4] Resolving packages...
--
11:16:37.454 | [2/4] Fetching packages...
11:16:37.467 | warning Pattern ["@nuxt/kit@npm:@nuxt/kit-edge@3.0.0-27385241.dccc0c9"] is trying to unpack in the same destination "/vercel/.cache/yarn/v6/npm-@nuxt-kit-3.0.0-27385241.dccc0c9-49da4c43c327c66c67ee368a7aad6f910d9bc153-integrity/node_modules/@nuxt/kit" as pattern ["@nuxt/kit@npm:@nuxt/kit-edge@latest"]. This could result in non-deterministic behavior, skipping.
11:16:53.541 | [3/4] Linking dependencies...
11:16:53.543 | warning "nuxt-windicss > vite-plugin-windicss@1.6.3" has unmet peer dependency "vite@^2.0.1".
11:16:53.546 | warning "nuxt3 > @nuxt/vite-builder > autoprefixer@10.4.2" has unmet peer dependency "postcss@^8.1.0".
11:16:53.546 | warning "nuxt3 > @nuxt/vite-builder > postcss-import@14.0.2" has unmet peer dependency "postcss@^8.0.0".
11:16:53.547 | warning "nuxt3 > @nuxt/vite-builder > postcss-url@10.1.3" has unmet peer dependency "postcss@^8.0.0".
11:16:58.060 | [4/4] Building fresh packages...
11:16:58.416 | Done in 21.53s.


</body>
</html>

**Comment by valetzx** [comment]
还是一样，会不会是token出问题了，但是为什么有些文件夹读有些不读呢。

**Comment by valetzx** [comment]
![image](https://user-images.githubusercontent.com/45054400/154191991-1896a0c1-6a6a-4196-b1ea-f8e41c010c60.png)

**Comment by valetzx** [comment]
[https://allblog.vercel.app/article/01VC3T5Y6PG4YVK7IA3RF24RDUSLCBSOUJ](https://allblog.vercel.app/article/01VC3T5Y6PG4YVK7IA3RF24RDUSLCBSOUJ)
现在是，以前的blog内容都可以显示，但是没在主页渲染出来。

**Comment by arect** [comment]
直接fork你的仓库部署也没有问题：[https://allblog-five.vercel.app/](https://allblog-five.vercel.app/)，你把博客文件夹截图我看看吧。

**Comment by valetzx** [comment]
我把`settings.json`删了新建后，问题解决了。感谢，麻烦你了。
