### ISSUE TITLE
当refresh token不活跃而过期

### ISSUE THREAD

**Issue by valetzx** [arect/onedrive_blog#6]
大佬，最近还好吗。我的blog请求好像坏了，这是refresh token的问题吗
![image](https://user-images.githubusercontent.com/45054400/162684022-3c9d40d0-a135-4b91-bbc1-0a353165aaf2.png)
![image](https://user-images.githubusercontent.com/45054400/162684157-373a5ef2-93ce-4506-99d0-c5d3f5a4c6ea.png)
是要重新获取reftoken吗，明明有在使用为什么会过期呢，这种可以让他自动刷新吗。感谢

**Comment by arect** [comment]
看错误确实是refresh token过期了，因为博客是无状态的，所以没办法做自动更新，需要再手动更新一下。

**Comment by arect** [comment]
可能是因为博客最近访问量比较少，我的也失效过几次。

**Comment by valetzx** [comment]
![image](https://user-images.githubusercontent.com/45054400/162689483-73f0a7a3-d322-43b8-9d28-3e982fcf74b5.png)
访问少应该是不可能的，我设置了一些定时访问。理论上应该可以在本地缓存refresh token让他自动刷新调用吧。

**Comment by valetzx** [comment]
让他在访问的时候刷新（）

**Comment by arect** [comment]
因为Vercel无法更新数据，所以如果要缓存数据的话需要用到数据库一类的东西，这就比较复杂了。缓存在浏览器是不可取的，这样会让访问者获得你onedrive所有文件的读取权限。
既然你会每天调用访问的话，其实可以直接访问api来续期。

**Comment by arect** [comment]
这个项目更新了好多了……（我太咸鱼了）
我觉得可以尝试一下这个项目，把网盘当成博客用，甚至效果会比我的更好。
最近在忙毕设，大概是没有时间修改了。

**Comment by arect** [comment]
诚惶诚恐，等忙完一定好好改😂

**Comment by valetzx** [comment]
好的感谢

**Comment by valetzx** [comment]
可以看一下，https://alist.pigpigeon.repl.co/ 你说的应该就是这样效果吧，但是真的是你的程序比较方便，如果有空真的可以做个预览图展示！

**Comment by arect** [comment]
在我提到的项目里，如果用markdown写文章的话，是可以直接渲染的。

**Comment by valetzx** [comment]
哈哈，突然看到这是nextjs项目，正在尝试在别的平台部署。
![image](https://user-images.githubusercontent.com/45054400/162696327-9b35fdd3-9015-4dc9-bf67-f98990cecf16.png)

毕设加油

**Comment by arect** [comment]
谢谢。
