### ISSUE TITLE
自己环境构建，不使用vercel

### ISSUE THREAD

**Issue by valetzx** [arect/onedrive_blog#7]
![image](https://user-images.githubusercontent.com/45054400/163081800-69e08921-b872-449a-ad0b-5f8eedd1abb0.png)
![image](https://user-images.githubusercontent.com/45054400/163081899-2d9c90b4-35bb-4abb-8f29-cd33cd811d36.png)
ni你好，为什么我的环境可以构建项目却不能 预览

**Comment by valetzx** [comment]
![image](https://user-images.githubusercontent.com/45054400/163082498-c991fff6-dd55-4c78-a662-788fd4b21733.png)

**Comment by arect** [comment]
用`nuxi dev`进行开发预览，`nuxi build`编译，编译后用`node .output/server/index.mjs`进行生产预览。不知道你要的是不是这个。

**Comment by arect** [comment]
nuxt版本可能变化，我也不清楚目前的操作，毕竟nuxt3还是beta版本。

**Comment by valetzx** [comment]
![image](https://user-images.githubusercontent.com/45054400/163090251-30571f29-e598-48af-9e7c-dcfd414fbed5.png)
出现这种是不是好了？（但是似乎访问无效）

**Comment by arect** [comment]
对，但是我不清楚你的本地环境，你应该访问3000端口。

**Comment by valetzx** [comment]
![image](https://user-images.githubusercontent.com/45054400/163090787-4433318d-69bc-41e5-856d-a9bd5e2f05a4.png)
我是云环境，我是不是可以下载.output之后在本地一样 `node .output/server/index.mjs` 然后访问 3000

**Comment by arect** [comment]
需要安装nodejs，安装以后就可以下载然后在本地访问了。

**Comment by valetzx** [comment]
![image](https://user-images.githubusercontent.com/45054400/163093159-f83e57fb-a190-4140-8983-b9e40ecfed17.png)
绝了本地可以，不知道那个云平台为啥不行

**Comment by valetzx** [comment]
![image](https://user-images.githubusercontent.com/45054400/163094128-9d911056-7829-439a-95dc-1062141b6d48.png)
另一个nodejs网页项目是这样写的 可以访问，可否劳烦看一下，如果有空的话（

**Comment by valetzx** [comment]
绝了不会是这个问题吧https://github.com/nuxt/framework/discussions/3520

**Comment by arect** [comment]
不是没有这个可能……

**Comment by valetzx** [comment]
![image](https://user-images.githubusercontent.com/45054400/163124688-219bdbc0-568f-4714-a704-f5d8c662ea3f.png)
我不知道这个要写哪

**Comment by arect** [comment]
大概的意思是，他用的PM2平台部署项目，类似于在Vercel上部署，所以对你的帮助可能不大。

**Comment by valetzx** [comment]
![image](https://user-images.githubusercontent.com/45054400/163124981-19cc419b-8cbf-4659-905d-85f191791d2b.png)
而且确实是可以内网访问了（）

**Comment by arect** [comment]
这个有可能是PM2平台的配置文件。

**Comment by valetzx** [comment]
PM2应该是个pack
![image](https://user-images.githubusercontent.com/45054400/163125164-b7fbcdd8-51ef-498b-907a-8374a3100105.png)

**Comment by arect** [comment]
https://v3.nuxtjs.org/guide/deployment/pm2

**Comment by arect** [comment]
或者你可以试一下`npx nuxi dev -h 0.0.0.0 -p 3000`这条命令，这个是开发预览，监听0.0.0.0

**Comment by valetzx** [comment]
![image](https://user-images.githubusercontent.com/45054400/163126549-34bcdf07-cef9-468d-ac83-c53f8a47acc1.png)
输出

**Comment by arect** [comment]
这个是说node版本有点低吧，你试试在本地局域网能不能连上？然后再试试这条命令能不能连上？
比如电脑启动后，同一wifi下手机访问电脑的地址。

**Comment by valetzx** [comment]
![image](https://user-images.githubusercontent.com/45054400/163128460-c61a5086-269f-4e01-9fb5-9d35cfef8655.png)
一样，是只要运行 `npx nuxi dev -h 0.0.0.0 -p 3000` 吗要不要别的

**Comment by arect** [comment]
啊，我帮你试了，本地一切正常。

**Comment by arect** [comment]
要不你把package.json改成
```json
{
  "private": true,
  "scripts": {
    "dev": "nuxi dev",
    "build": "nuxi build",
    "start": "node .output/server/index.mjs"
  },
  "devDependencies": {
    "nuxt-windicss": "^2.1.1",
    "nuxt3": "^3.0.0-27333874.279bfdc"
  },
  "dependencies": {
    "axios": "^0.24.0",
    "marked": "^4.0.7"
  }
  "config": {
    "nuxt": {
      "host": 0.0.0.0
    }
  }
}
```
试试？

**Comment by valetzx** [comment]
![image](https://user-images.githubusercontent.com/45054400/163131043-0f536312-2e4f-4a4f-a134-3124d8af9248.png)
刚刚看到个这个，但是好像也没用 好难 ）这output有别的办法启动吗 ）

**Comment by valetzx** [comment]
![image](https://user-images.githubusercontent.com/45054400/163132216-ba5f6314-2d6f-454c-8722-9a75bbb7172a.png)
不试了（晚点在看吧）

**Comment by valetzx** [comment]
![image](https://user-images.githubusercontent.com/45054400/163157512-1f6b003d-f592-42e5-9c47-952d95021f54.png)
额 完成了 用的是  `npm run dev`

**Comment by valetzx** [comment]
已完成：https://blog.pighog.repl.co 再次感谢

**Comment by arect** [comment]
没事。

**Comment by valetzx** [comment]
我吐大血，昨天晚后来死活不能构建，都不能构建了也不知道为什么。删环境重来了十几次。
![VJ`56FC_33VDK}JCRFP557G](https://user-images.githubusercontent.com/45054400/163291905-2794e264-a088-4145-b9f7-487e2ec126e9.png)

**Comment by arect** [comment]
原文件覆盖一下？

**Comment by valetzx** [comment]
我clone你的仓库，我的仓库，昨天构建好备份的仓库都试过了。好像是nuxt3更新了

**Comment by valetzx** [comment]
mr每日一问，可以build 可以本地preview不能外网（）
![image](https://user-images.githubusercontent.com/45054400/163496382-5604ece9-9b54-4cde-bcac-f4aa6d50109a.png)
![image](https://user-images.githubusercontent.com/45054400/163496406-c87f474c-81f1-4ae2-bbe1-1175eed3d305.png)
![image](https://user-images.githubusercontent.com/45054400/163496536-b3cfb963-580c-4a41-9206-3a56be9aa9d7.png)

**Comment by arect** [comment]
关于这个我不清楚😂

**Comment by valetzx** [comment]
可以让 `node .output/server/index.mjs` 指定监听0.0.0.0吗，不用localhost

**Comment by arect** [comment]
我搜了一下找到这个：[https://www.bootschool.net/article/5dc3f868f60a31379ef35fd5](https://www.bootschool.net/article/5dc3f868f60a31379ef35fd5)，可以看一下有没有用。

**Comment by valetzx** [comment]
好的谢谢，晚点试一下 。
